# Generated by Django 3.0.4 on 2020-04-09 17:15

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('_image_hash', models.BinaryField(default=None, max_length=16, null=True)),
                ('_thumbnail_hash', models.BinaryField(default=None, max_length=16, null=True)),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Residential'), (1, 'Commercial'), (2, 'Schools'), (3, 'Enhancements'), (4, 'Sustainability')])),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=gallery.models.GalleryImage.relative_path)),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to=gallery.models.GalleryImage.relative_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
