# Generated by Django 3.0.4 on 2020-04-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselimage',
            old_name='_hash',
            new_name='_image_hash',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='_thumbnail_hash',
            field=models.BinaryField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='carousel/'),
        ),
    ]
